name: Jobs

on:
  push:
  pull_request:

jobs:
  test-1_13:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.13.0"
          check-latest: true

      - name: Test
        working-directory: ./testdata
        shell: sudo --preserve-env=PATH bash -e {0}
        run: |
          go version
          go test

  test-stable:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup Go Stable
        uses: actions/setup-go@v6
        with:
          go-version: stable
          check-latest: true

      - name: Test Go Stable
        working-directory: ./testdata
        shell: sudo --preserve-env=PATH bash -e {0}
        run: |
          go version
          go mod edit -go $(go version | grep -Eo [0-9]+\.[0-9]+ | head -1)
          go get -u golang.org/x/net@latest
          go mod tidy
          go test
